version: v1.1.0

oauth2_provider:
    url: "http://hydra:4445"
log:
    level: trace
    format: text
    leak_sensitive_values: true
dsn: memory
serve:
  public:
    base_url: http://localhost:4433/
    cors:
      enabled: True
  admin:
    base_url: http://kratos:4434/

identity:
    default_schema_id: default
    schemas:
        - id: default
          url: file:///etc/config/kratos/identity.schema.json
selfservice:
    allowed_return_urls:
      - http://localhost:4455/ui/login
      - http://localhost:4455/ui/reset_email
      - http://localhost:4455/ui/reset_password
      - http://localhost:4455/ui/reset_complete
    default_browser_return_url:
        http://localhost:4455/ui/
    flows:
        error:
            ui_url: http://localhost:4455/ui/error
        login:
            ui_url: http://localhost:4455/ui/login
        recovery:
            enabled: True
            ui_url: http://localhost:4455/ui/reset_email
            use: code
            after:
                default_browser_return_url: http://localhost:4455/ui
                hooks:
                    - hook: revoke_active_sessions
        settings:
            ui_url: http://localhost:4455/ui/reset_password
        registration:
            after:
                oidc:
                    hooks:
                    - hook: session
    methods:
        password:
            enabled: True
        code:
            enabled: True
        oidc:
            enabled: True
            config:
                providers:
                - id: "github"
                  provider: "github"
                  mapper_url: "file:///etc/config/kratos/schema.jsonnet"
                  scope: ["user:email"]
                  label: Github
courier:
    smtp:
        connection_uri: smtps://test:test@mailslurper:1025/?skip_ssl_verify=true
